[package]
name = "sov-admin-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
sov-core = { path = "../sov-core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde_yaml = "0.9"
serde_json = "1"
