[package]
name = "sov-transport"
version = "0.1.0"
edition = "2024"

[dependencies]
sov-core = { path = "../sov-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
